# ==========================================
# User Project Configuration
# ==========================================

# 1. 项目名称 (生成的 PDF 文件名)
NAME   = Hypoxanthine-LaTeX

# 2. 主文件入口
MAIN_FILE = main.tex

# 3. 指向 Hypoxanthine-LaTeX 仓库的路径 
# (如果在子目录，通常是 ./Hypoxanthine-LaTeX)
HYPO_PATH = ./Hypoxanthine-LaTeX

# ==========================================
# Include Core Logic
# ==========================================
include $(HYPO_PATH)/make/Hypoxanthine.mk
